version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./client/src:/app/src

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./server:/app
